const SECOND_DURATION_IN_MILLISECONDS = 1000;
const MINUTE_DURATION_IN_MILLISECONDS = 60 * SECOND_DURATION_IN_MILLISECONDS;
const HOUR_DURATION_IN_MILLISECONDS = 60 * MINUTE_DURATION_IN_MILLISECONDS;
const DAY_DURATION_IN_MILLISECONDS = 24 * HOUR_DURATION_IN_MILLISECONDS;

export { SECOND_DURATION_IN_MILLISECONDS, MINUTE_DURATION_IN_MILLISECONDS, HOUR_DURATION_IN_MILLISECONDS, DAY_DURATION_IN_MILLISECONDS };